# input data
# base_dir: /home/chialiang86/Desktop/3DCV/hw/3DV-2022
data_dir: /home/chialiang86/Desktop/3DCV/hw/3DV-2022/data/chair_img_pc_voxel_mesh
dtype: "point" # "point" "voxel"
n_points: 2048

# vision model
arch: resnet18

# training
lr: 0.0004
max_iter: 50

# dataloader
batch_size: 10
num_workers: 2

# logger
log_freq: 1000

# checkpoint
save_freq: 1
load_checkpoint: False

# eval
vis_freq: 1
load_eval_checkpoint: True

